### ISSUE TITLE
Some block comments are not closed properly

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/comment-regex#3]
Would you like to support option `loose` for block comment that is not closed properly? EG:

```js
/*
var test = 'test';
```
is actually a "valid" block comment :(

**Comment by sindresorhus** [comment]
It's not.

```
❯ node -e "/*\nvar test = 'test';"
[eval]:1
/*\nvar test = 'test';
^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:73:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
```
